### ISSUE TITLE
Category color changes in stack()

### ISSUE THREAD

**Issue by imandr** [scikit-hep/histbook#38]
I fill the histogram with a category axis in several iterations and I want to see it after each iteration, e.g.:

```
h = Hist(bin("x", 10, 0, 1), groupby("type"))

x = np.random.random((100,))
h.fill(type="A", x=x*x)
h.stack("type").area("x").to(canvas)
```
Here is the plot:
![visualization 5](https://user-images.githubusercontent.com/21269715/41820113-1f128e9c-7792-11e8-9886-1a0bcf5fd32d.png)

Here comes second iteration:
```
x = np.random.random((100,))
h.fill(type="B", x=1-x*x)
h.stack("type").area("x").to(canvas)
```

![visualization 6](https://user-images.githubusercontent.com/21269715/41820127-4fb4a77e-7792-11e8-93f3-0838bdbfbb25.png)

Notice that the color for type=A histogram has changed from blue to orange and type=B is blue now. It would be good to make subplots keep their representation attributes.

Btw, it works correctly with overlay()

**Comment by jpivarski** [comment]
The colors are assigned by Vega-Lite and there's some way to set them— control that I'll pass through to the user somehow. However, they're probably in order of the data points themselves. That order is not preserved by `_content`, which is a dict. Maybe the content for groupby stuff should be an OrderedDict? dict already introduces a performance bottleneck, OrderedDict could be worse.

Nothing would be _broken_ by (optionally?) making the dict ordered. All of the checks are `isinstance(x, dict)`. Maybe that should be a groupby constructor option.

In the farther future, I should probably replace the dict representation with something contiguous in memory. Probably the easiest way would be something based on ChunkedArrays from the new awkward-array library I'm developing.

If there are no issues with overlays and the log plots are looking okay, can I close the other issue and merge that branch into master? I'll consider this one closed when I add the OrderedDict option to groupby.

**Comment by imandr** [comment]
Log plots with overlays do not look ok. See my last comment on issue 37.

I meant to say that overlay preserves colors unlike stack. Or maybe I was just lucky.

**Comment by imandr** [comment]
I think you could add an attribute to the Hist with categorical axis, which would be a list of all the category axis plotted so far. This list would be used only set the order of the subplots inside stack() or overlay(), not for filling. And if a category value is not in the list, then append it.

```
class Hist:
    def __init__(...):
        # for each category axis:
        self.CategoryOrders = {}

    def stack(axis_name):
        category_order = self.CategoryOrders.get(axis_name)
        if category_order is None:
            category_order = []
            self.CategoryOrders[axis_name] = category_order
        for value in values_for_axis(axis_name):
            if not value in category_order:
                 category_order.append(value)
        for value in category_order:
            add_subplot(value)

**Comment by jpivarski** [comment]
Wait a minute— I just realized that this is stack: you have the power to set the order by hand. The `stack` method [has an `order` parameter](http://histbook.readthedocs.io/en/latest/plotting.html#histbook.vega.PlottingChain.stack):

```python
>>> beside(h.stack("type", order=["A", "B"]).area("x"),
           h.stack("type", order=["B", "A"]).area("x")).vegascope()
```

![vegascope 2](https://user-images.githubusercontent.com/1852447/41858225-f1f4e9be-785e-11e8-9f26-89ba299cd3bd.png)

An automated "sort stability" fix should tap into that mechanism. Stay tuned.

**Comment by imandr** [comment]
Using explicit order here is not always convenient because you either need to use all _possible_ category values or all values filled into the histogram so far. 

If you use all possible values, the legend will contain all of them even if the histogram has only some of them filled, which is not ideal:

![visualization 3](https://user-images.githubusercontent.com/21269715/41859999-188ec7a8-7863-11e8-823e-a5383c96fd32.png)

So the best option is to use only those values filled into histogram so far, but in case of iterative displaying, that means using pretty much using same logic as I described earlier, only outside of the histogram class.

**Comment by jpivarski** [comment]
How about this?

```python
>>> import numpy as np
>>> from histbook import *
>>> h = Hist(bin("x", 10, 0, 1), groupby("type", keeporder=True))   # new option
>>> x = np.random.random((10000,))
>>> h.fill(type="A", x=x*x)
>>> h.stack("type").area("x").vegascope()
```

![vegascope](https://user-images.githubusercontent.com/1852447/41861124-07aac916-7866-11e8-90db-c10944e2a77a.png)

```python
>>> x = np.random.random((10000,))
>>> h.fill(type="B", x=1-x*x)
>>> h.stack("type").area("x").vegascope()
```

![vegascope 1](https://user-images.githubusercontent.com/1852447/41861136-0e0af1b4-7866-11e8-9795-5e2adba5c303.png)

```python
>>> x = np.random.random((10000,))
>>> h.fill(type="C", x=x*x)
>>> h.stack("type").area("x").vegascope()
```

![vegascope 2](https://user-images.githubusercontent.com/1852447/41861143-13e18a4e-7866-11e8-9cb8-488f7aaf894d.png)

```python
>>> x = np.random.random((10000,))
>>> h.fill(type="D", x=1-x*x)
>>> h.stack("type").area("x").vegascope()
```

![vegascope 3](https://user-images.githubusercontent.com/1852447/41861153-1943257e-7866-11e8-893b-e479d5f97444.png)

**Comment by imandr** [comment]
I am using issue-37 branch.

I get this error, which I think is related to JSON serialization:

```
Exception in thread Thread-44:
Traceback (most recent call last):
  File "/home/ivm/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/ivm/bigdata/qworker/QWorker/SocketGangContract.py", line 163, in run
    self.Contract.updateReceived(self, data_chunks, events_delta)
  File "/home/ivm/bigdata/qworker/QWorker/MyThread.py", line 15, in smethod
    out = method(self, *params, **args)
  File "/home/ivm/bigdata/qworker/QWorker/SocketGangContract.py", line 237, in updateReceived
    self.CallbackDelegate.updateReceived(worker.WID, data, nevents_delta)
  File "/home/ivm/bigdata/qworker/QWorker/MyThread.py", line 15, in smethod
    out = method(self, *params, **args)
  File "/home/ivm/bigdata/qworker/QWorker/StripedJob.py", line 36, in updateReceived
    self.DataCallbackDelegate.updateReceived(data_dict, nevents)
  File "/home/ivm/bigdata/qworker/QWorker/MyThread.py", line 15, in smethod
    out = method(self, *params, **args)
  File "/home/ivm/bigdata/qworker/QWorker/StripedJob.py", line 125, in updateReceived
    ha.add(data)
  File "/home/ivm/bigdata/qworker/QWorker/HistBookInterface.py", line 34, in add
    h = Hist.fromjson(json.loads(dump))
  File "build/bdist.linux-x86_64/egg/histbook/hist.py", line 730, in fromjson
    out = Hist(*[histbook.axis.Axis.fromjson(x) for x in obj["axis"]], weight=obj.get("weight", None), filter=obj.get("filter", None), defs=obj.get("defs", None), attachment=obj.get("attachment", None))
  File "build/bdist.linux-x86_64/egg/histbook/axis.py", line 204, in fromjson
    return groupby.fromjson(obj)
  File "build/bdist.linux-x86_64/egg/histbook/axis.py", line 272, in fromjson
    return groupby(obj["expr"], obj["keeporder"])
KeyError: 'keeporder'
```

**Comment by jpivarski** [comment]
Yes— of course— it's a new property. I'll pass that through.

**Comment by jpivarski** [comment]
You know, I don't see anything wrong with the JSON serialization. Could it be that you're trying to deserialize old objects with new code?

The JSON format hasn't been made schema-evolving for archive. I don't foresee frequent changes anyway— this was a surprise.

**Comment by imandr** [comment]
Which branch is this fixed in ? I am using "issue-37" and colors are unstable.

**Comment by jpivarski** [comment]
It is in that branch and I observed stable colors when using the `keeporder=True` argument.

**Comment by imandr** [comment]
Ah yes, thanks !

**Comment by imandr** [comment]
I was wondering, maybe keeporder should always be True ? 
I can not think of a case when someone would actually want colors to change..

**Comment by jpivarski** [comment]
If it's not animated, the colors aren't "changing," and we've paid the penalty for an OrderedDict rather than a dict. The collection order also doesn't have a meaning when you combine histograms from different sources. The cases in which collection order matters are special, rather than the other way around.
